package(default_visibility = ["//visibility:public"])

java_library(
    name = "util",
    srcs = [
        "NumberConversion.java",
    ],
    deps = [
        "//proto:shared_java_proto",
        "@com_google_protobuf_java//:protobuf_java"
    ],
)