package(default_visibility = ["//visibility:public"])

filegroup(
    name = "application",
    srcs = [
        "application.conf",
    ]
)

filegroup(
    name = "backtest",
    srcs = [
        "backtest.conf",
    ]
)

filegroup(
    name = "email",
    srcs = [
        "email.conf",
    ]
)

filegroup(
    name = "exchanges",
    srcs = [
        "exchanges.conf",
    ]
)

filegroup(
    name = "logger",
    srcs = [
        "simplelogger.properties",
    ]
)