package(default_visibility = ["//visibility:public"])

proto_library(
    name = "shared",
    srcs = ["shared.proto",],
)

java_proto_library(
    name = "shared_java_proto",
    deps = [":shared",],
)
